### ISSUE TITLE
A problem when I want to auth my password

### ISSUE THREAD

**Issue by cjuexuan** [etaty/rediscala#100]
object AuthDemo extends  App{
  implicit  val akkaSystem = akka.actor.ActorSystem()
  val redis = RedisClient(password = Some("1234"))
  redis.ping()
  redis.shutdown()
}

when I run the code like this The problem is  my redis-server will shutdown .

**Comment by etaty** [comment]
Yes it is normal
http://redis.io/commands/shutdown

You want to use `redis.stop` to disconnect
https://github.com/etaty/rediscala/blob/7764e07b8effd6752c135f19c6ab74705b6c8e4e/src/main/scala/redis/Redis.scala#L64-L70

**Comment by cjuexuan** [comment]
thank you
