### ISSUE TITLE
Logging support for queries?

### ISSUE THREAD

**Issue by danishin** [etaty/rediscala#101]
Hello, first of all, thank you so much for working on this. What a great library.

I'm looking for something like other jdbc-library-like query logging supports (for example, statement logging in SQL). I've set `redis` to `debug` level in `logback.xml` but it seems to only support the `actor` connection and disconnection and the kind but not logging for the actual queries.

Am I missing something here or is it not supported? Thank you!

**Comment by etaty** [comment]
It is not supported so far.

Redis is just communicating with simple commands while SQL is a language (that is often generated), so I am not sure it is useful.

Otherwise you have http://redis.io/commands/MONITOR
> MONITOR is a debugging command that streams back every command processed by the Redis server. It can help in understanding what is happening to the database.

**Comment by danishin** [comment]
Thanks for the suggestion. I often like to log out everything when there is a need for debugging so I find this useful but I agree that it's not essential enough to be part of the library.

How should I go about sending `MONITOR` command? So far, I couldn't find `rediscala` command to send arbitrary command? Thanks for your help

**Comment by etaty** [comment]
`monitor` is a cli command (you don't use it in a normal codebase, so it is not included in rediscala)
But you can use it with the redis console : `redis-cli` on your terminal

**Comment by danishin** [comment]
I guess that'll do the job. Thanks for your help!
