### ISSUE TITLE
LRANGE get id for each result

### ISSUE THREAD

**Issue by eduardofcbg** [etaty/rediscala#102]
Is there a way to get the id of each element returned by  an LRANGE?
Thanks.

**Comment by etaty** [comment]
I don't think so as the original command does not expose that (
http://redis.io/commands/lrange )
In scala, for if you want to have the index on a collection you can use
zipWithIndex

   1.

   List("a", "b", "c").zipWithIndex = List(("a", 0), ("b", 1), ("c", 2))

http://www.scala-lang.org/api/current/index.html#scala.collection.immutable.Seq

**Comment by eduardofcbg** [comment]
I was mistaken to think that the original command exposed that feature.
Thanks a lot for the suggestion, that will solve my current problem.
