### ISSUE TITLE
max should before min for zrevrangebyscore command

### ISSUE THREAD

**Issue by ylgrgyq** [etaty/rediscala#110]
Hi, thanks for this brilliant lib.

Maybe I found a bug and please check it.

For [zrevrangebyscore](http://redis.io/commands/zrevrangebyscore) command, max should before min but in redis.api.sortedsets.Zrevrangebyscore it encodes this command uses Zrangebyscore.buildArgs(...) which encodes parameter min before max. I think the order is not correct.

**Comment by etaty** [comment]
Thanks
It has been reported and resolved in #98 

try with deps ` "com.github.etaty" %% "rediscala" % "1.6.0-SNAPSHOT"`

**Comment by ylgrgyq** [comment]
great!
