### ISSUE TITLE
Bad performance for "hgetall"

### ISSUE THREAD

**Issue by mkotsbak** [etaty/rediscala#112]
Trying to get a hashmap with 10 000 simple elements like this:

```
(tagkey8193,tagvalue8193)
(tagkey8748,tagvalue8748)
(tagkey6678,tagvalue6678)
(tagkey9674,tagvalue9674)
```

is extremely slow. It takes around 1 seconds to get all those values out, with a simple mapping. I suspect the algorithm to parse the results is too slow, and maybe is performing exponentially slow with increasing values.

**Comment by etaty** [comment]
This is were thing are happening: https://github.com/etaty/rediscala/blob/ecd2c7bcafdaf17db0b5b2357b7a2d4b309a6e85/src/main/scala/redis/api/Hashes.scala#L26

**Comment by etaty** [comment]
Oh I see, it is iterating twice on the reply
https://github.com/etaty/rediscala/blob/ecd2c7bcafdaf17db0b5b2357b7a2d4b309a6e85/src/main/scala/redis/api/Hashes.scala#L31
Also I could give a sizeHint to the map

**Comment by etaty** [comment]
https://github.com/etaty/rediscala/blob/ecd2c7bcafdaf17db0b5b2357b7a2d4b309a6e85/src/main/scala/redis/protocol/RedisProtocolReply.scala#L171
Here we could also use a Seq builder and give a sizeHint

**Comment by mkotsbak** [comment]
Japp, just move the map inside the builder?

**Comment by mkotsbak** [comment]
Moved back to https://github.com/debasishg/scala-redis with connection pooling. The same test (with 20k values) performs around 15 req/s.

**Comment by etaty** [comment]
It should be resolved now
```
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "com.github.etaty" %% "rediscala" % "1.6.0-SNAPSHOT"
```
Tell me if you don't see similar perf ( I can do 15 hgetall/s with 10k elements with one single connection)

**Comment by mkotsbak** [comment]
Hmm, much better after the modifications:
Requests per second:    3.72 [#/sec] (mean)

but it still seems far behind scala-redis with the same data in the DB:

Requests per second:    14.45 [#/sec] (mean)

**Comment by etaty** [comment]
Thanks,
I will try to do a benchmark diff with scala-redis
Can you post the code you are running in a gist?

**Comment by mkotsbak** [comment]
I'm sorry, the code cannot be disclosed, but it should be easy to reproduce using scala-redis future with connection pool example. Is this project using multiple connections, or just one?

**Comment by etaty** [comment]
Hum I see, the main difference is the number of connection to the redis server.
A `RedisClient` is just one connection while scala-redis use a pool in your bench.
But yeah I will publish some benchmarks.

**Comment by etaty** [comment]
Okay,
I did rewrite the redis reply decoder, so it can keep a much closer state of what has been decoded.  Something like progressive decoding (or async decoding).

Before I was decoding a full redis response, and if I did not have the full response, I was starting again when receiving the next packet. It works with small response. But the response for HGETALL with 10000 hashes is around 1MB! So the decoding is deadly slow.

Conclusion is that now I am even faster than scala-redis. I will clean and post the result before the end of the year.

**Comment by mkotsbak** [comment]
Great! I can't see any code here yet?

**Comment by etaty** [comment]
I create a PR #119

**Comment by etaty** [comment]
snapshot available
```
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "com.github.etaty" %% "rediscala" % "1.6.0-SNAPSHOT"
```
