### ISSUE TITLE
Make Redis.dispatcher configurable

### ISSUE THREAD

**Issue by wb14123** [etaty/rediscala#122]
`Redis.dispatcher` is not configurable for now. Though the behavior of this dispatcher could be config, the RedisActor cannot use the same dispatcher with the other actors (Play or Spray actors for example). It is kind of a big deal if I want the number of threads to be the same as CPU cores, and all the actors use all of these threads.

So I'd like the name of dispatcher could be configurable. Here I come up with three methods:

* Pass the name as a param of `RedisClient`, `RedisClientPool`, etc.
* Use implict value.
* Use Typesafe config, config it in the file.

All the methods could have a default value so that they don't break the compatibility. Which one is better for you? I can implement it.

**Comment by etaty** [comment]
I think implicit value + default value (Redis. dispatcher) would be the best

**Comment by etaty** [comment]
`implicit dispatcher : MessageDispatcher = Redis.dispatcher`
```
Redis { 
def dispatcher(implicit ActorSys) = system.lookup("...default here")
}
```
Also can you replace all the https://github.com/etaty/rediscala/blob/5b82c8f5402e26b71671069a3b4da192a4adadbf/src/main/scala/redis/Redis.scala#L32
with the implicit dispatcher (avoid context switching, so that should improve performance a little also in some case)

**Comment by etaty** [comment]
I am also curious of how the threads behave when there is only one single redisclient (it might be a waste of resource, always jumping around). have to investigate that.

**Comment by wb14123** [comment]
The cost of an actor's context switch should be smaller than a thread's. And the behavior of actors' context switch could be configured by `throughtput` of the dispatcher. We have more control for dispatchers than for OS threads.

I will implement the configuration this weekend.
