### ISSUE TITLE
Clustering is not supported

### ISSUE THREAD

**Issue by 1178615156** [etaty/rediscala#145]

**Comment by alexmnyc** [comment]
Any chance RedisCluster can be published as a milestone release with 1.7.0-M1 ?

**Comment by Uxio0** [comment]
https://github.com/etaty/rediscala/issues/155

**Comment by etaty** [comment]
Hey,
`1.7.0` is available with redis cluster support 
`libraryDependencies += "com.github.etaty" %% "rediscala" % "1.7.0"`
