### ISSUE TITLE
Incorrect results while using RedisClientMasterSlaves. 

### ISSUE THREAD

**Issue by chitralverma** [etaty/rediscala#148]
@etaty hi, I have found your Redis API very useful and the benchmark scores seem real promising.
I'm actually working on a tiny project that requires max throughput possible. 

I have a master-client setup (think 3 servers :  i1,i2,i3) where i3 is master and other 2 are slaves. Now, I'm trying the RedisClientMasterSlaves method to create the client (say, redisClient) for the setup. So, I do 
`redisClient.select(5)`
`redisClient.set("testkey","testvalue")`

they work just fine.
then i go for`redisClient.get("testkey")`. I get a None. I realized in case of set() the correct table is being selected, this doesn't happen in case of get(). I got the right results when I explicitly mentioned the db index while defining the slave servers. Can you tell me if there is a work around or am I missing something?

**Comment by etaty** [comment]
Usually multidb/select in redis is deprecated, because it makes the
connection stateful instead of being stateless.

**Comment by chitralverma** [comment]
Ok! So, what do you suggest if my use case demands stateful connections to a master slave setup?

**Comment by etaty** [comment]
You can select all the slaves and change the database they operate on.
https://github.com/etaty/rediscala/blob/422375fe6487d033cfe388d27b161876fb74ef0a/src/main/scala/redis/RedisPool.scala#L152
But I still advise to avoid this kind of things, you will generate weird bug if another part of this system use another database.
The best would be to connect to the right database and never select another.
Create a RedisClientMasterSlaves for each database you operate on.
