### ISSUE TITLE
support Scala 2.12

### ISSUE THREAD

**Issue by xuwei-k** [etaty/rediscala#154]

**Comment by GhaziTriki** [comment]
@etaty Can you please deploy the version for scala 2.12? It is highly needed

**Comment by etaty** [comment]
in progress #159

**Comment by etaty** [comment]
Hey,
`1.8.0-SNAPSHOT` support scala 2.12
libraryDependencies += "com.github.etaty" %% "rediscala" % "1.8.0-SNAPSHOT"
Hopefully, I will make it stable in a few days ;)

**Comment by GhaziTriki** [comment]
@etaty Thanks. We are waiting for it.

**Comment by smdmts** [comment]
@etaty Hi, 1.8.0-SNAPSHOT is missing in maven central. would you please to publish that?

**Comment by jvvasques** [comment]
@etaty `1.8.0-SNAPSHOT' is still missing on maven central

**Comment by etaty** [comment]
Could you double check? (did you add the snapshot repo in sbt)
I can see them here :
https://oss.sonatype.org/content/repositories/snapshots/com/github/etaty/rediscala_2.11/1.8.0-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/com/github/etaty/rediscala_2.12/1.8.0-SNAPSHOT/

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/github/etaty/rediscala_2.12/1.8.0-SNAPSHOT/ is sonatype snapshot repo, not maven central.

@smdmts and @jvvasques want to `1.8.0 final` version on http://repo1.maven.org/maven2/com/github/etaty/rediscala_2.12 , right?

**Comment by jvvasques** [comment]
Yes @xuwei-k 👍

**Comment by smdmts** [comment]
@etaty Thank you. I'll add snapshot repo and wait `1.8.0 final` on maven central.

**Comment by etaty** [comment]
I just published the stable version 1.8.0 working with scala 2.11 and 2.12
`libraryDependencies += "com.github.etaty" %% "rediscala" % "1.8.0"`
