### ISSUE TITLE
What repo is 1.8.0-SNAPSHOT in ?

### ISSUE THREAD

**Issue by unoexperto** [etaty/rediscala#165]
I'm sorry for asking here but what repo is 1.8.0-SNAPSHOT in ? I checked http://mvnrepository.com/artifact/com.github.etaty/rediscala_2.11 and here http://dl.bintray.com/etaty/maven/com/etaty/rediscala/rediscala_2.11/

**Comment by smdmts** [comment]
@unoexperto Hi, see this thread. #154 
Currently, We have to add resolver of "https://oss.sonatype.org/content/repositories/snapshots/".
