### ISSUE TITLE
Geo support is missing from 1.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by 123avi** [etaty/rediscala#166]
@etaty  hi, 
couldn't find redis.api.geo on 1.8.0-SNAPSHOT at https://oss.sonatype.org/content/repositories/snapshots/com/github/etaty/rediscala_2.11/1.8.0-SNAPSHOT/
can you add it please ?

**Comment by etaty** [comment]
Can you check that it works with 
`libraryDependencies += "com.github.etaty" %% "rediscala" % "1.8.0"`

**Comment by 123avi** [comment]
Yeap, it seems to be there. thanks !
