### ISSUE TITLE
SBT warning

### ISSUE THREAD

**Issue by magmel48** [etaty/rediscala#167]
SBT project import
[warn] Unable to reparse com.github.etaty#rediscala_2.11;1.8.0-SNAPSHOT from sonatype-snapshots, using Sun Nov 20 18:06:02 EAT 2016

what is that and how it can be fixed?

scalaVersion := "2.11.8"
sbt.version=0.13.13

**Comment by etaty** [comment]
I have no idea.
I have released 1.8.0 yesterday
Could you try again with?
`libraryDependencies += "com.github.etaty" %% "rediscala" % "1.8.0"`

**Comment by magmel48** [comment]
@etaty no warnings with new version. Thank you! I think this issue can be closed.
