### ISSUE TITLE
Why is there no ByteString => T deserializer?

### ISSUE THREAD

**Issue by agemooij** [etaty/rediscala#3]
I can do `redis.set("key", MyCustomType(42))` as long as I have a valid RedisValueConverter in implicit scope for my custom type.

But when I do `redis.get("key")` all I get is a raw `Option[ByteString]` and I have to convert it back to my custom type myself.

Why is there not a `get[T: RedisValueDeserializer](key: String): Future[Option[T]]` with some basic support for common types (Strings, Ints, Longs, Booleans, Lists, Sets, Maps, etc.)? Then I can have my own `RedisValueDeserializer` in scope to deserialize my custom types.

**Comment by darshoka** [comment]
redis.get("mykey") is returning Future[Option[ByteString]] type , Then how i can deserialize and get the orginal data from the result ?

**Comment by darshoka** [comment]
why empty list " List() " is returning while using redis.get("myKey") ?
