### ISSUE TITLE
brpop, blpop operation need isMasterOnly = true

### ISSUE THREAD

**Issue by debop** [etaty/rediscala#46]
I ran brpop, blpop operation to Slave Client, occur not use in Readonly server.

but brpop, blpop not setting "isMasterOnly = true"

In Master-Slave env,  connect to slave server, and send blpop, brpop 
READONLY  *************

**Comment by etaty** [comment]
I think it is fixed now
https://github.com/etaty/rediscala/blob/790d76411acaca20ebde49e9a6369b1c6ecfceae/src/main/scala/redis/api/BLists.scala#L18
