### ISSUE TITLE
HTTP Basic Auth support

### ISSUE THREAD

**Issue by stanch** [etaty/rediscala#56]
Correct me if I’m wrong, but it seems there is no way to connect to a server that requires Basic Auth, e.g. RedisCloud.

**Comment by abhandaru** [comment]
Hi @stanch, I am probably facing the same issue. Would you mind sharing what your `RedisClient` instantiation code looks like? I have something that works locally but not on Heroku. Much appreciated.

**Comment by stanch** [comment]
@abhandaru I don’t think I have that code anymore, sorry!

**Comment by abhandaru** [comment]
All good. I squirmed around until it worked.

I needed to parse out the password by splitting the `userInfo` over the `:` delimiter.
Hesitated to do this at first because there is no `username` field in the `RedisClient` constructor, but this did not matter for a working Redis connection.

```
import java.net.URI

// Ensure your runtime app is set up
implicit val actSys: ActorSystem
val redisUrl = ...

// Client construction
val redisClient: RedisClient = {
  val redisUri = new URI(redisUrl)
  // Format for `userInfo` is "[username]:[password]" but sending username
  // through is unnecessary for the Heroku connection.
  val password = Option(redisUri.getUserInfo)
    .flatMap(_.split(":").lastOption)

  RedisClient(
    host = redisUri.getHost,
    port = redisUri.getPort,
    password = password
  )
}
```
