### ISSUE TITLE
Logging & loglevel for RedisWorkerIO

### ISSUE THREAD

**Issue by alexanderscott** [etaty/rediscala#66]
First of all, thank you for your efforts and contributions towards this package - it is very intuitive and useful.

However, the logging inside of RedisWorkerIO is a problem.  Currently it binds to the implicit ActorSystem's LoggingAdapter (context.system.log) and I haven't found a reasonable way to silence connection/disconnection logging.  It does not use getLogger like elsewhere in the code to provide for slf4j or log4j contextual logging.  The [loglevel in the reference.conf](https://github.com/etaty/rediscala/blob/master/src/main/resources/reference.conf#L2) is not applied to Redis actors at all.  

[Disconnections are set to WARNING level](https://github.com/etaty/rediscala/blob/master/src/main/scala/redis/actors/RedisWorkerIO.scala#L104), and reconnections are are INFO level.  This is very annoying and chatty to run against a production Redis instance which frequently disconnects long-lived redis clients (reconnection handled by the driver).

Could you please update the logging to mute the particularly egregious WARN levels or apply a specific LoggingAdapter (log4j or slf4j style)?  I have [forks for both](https://github.com/alexanderscott/rediscala) - can open a pull.  

Thank you!

**Comment by AlexLaviolette** [comment]
@alexanderscott I'm having trouble quieting the connection logging. Would you mind sharing what you added to the logback conf to fix it?

**Comment by alexanderscott** [comment]
@AlexLaviolette can quiet logging by adding this line into your logback.xml configuration file, which should live in your static resources dir:

```xml
 <logger name="redis" level="ERROR"/>
```
And add logback as a library dependency to the project:

```scala
libraryDependencies += "ch.qos.logback"  % "logback-classic" % "1.0.9"
```

Can set your `akka.loglevel` to whatever in config, but it should still obey the rules established by logback. 

Example logback.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<configuration>

    <logger name="redis" level="ERROR"/>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%date %X{akkaSource} %highlight(%-5level) %cyan(%logger{5}) - %msg %n</pattern>
        </encoder>
    </appender>

    <root level="DEBUG">
        <appender-ref ref="CONSOLE"/>
    </root>

</configuration>
```
