### ISSUE TITLE
Sentinel onSentinelDown Issue

### ISSUE THREAD

**Issue by mmoulou** [etaty/rediscala#71]
Hi 

I've a problem with SentinelMonitoredRedisClient when one of my sentinel instance is down, the sentinelClient Instance is removed from sentinelClients list but the actor try to reconnect to sentinel each 2 seconds. 

In case when  one or more sentinel instances will stay down, i'll have multiple actors tryin to reconnect to non-existing sentinel instances.

after search, i find that redisscala schedule reconnect when connection is closed (class RedisWorkerIO)

I'd like to not have this behavior in case when i use sentinelClient.

Thanks

**Comment by mmoulou** [comment]
Up

**Comment by etaty** [comment]
Hi, you are probably right, but i don't have the time to write a fix for sentinel.
I invite you to submit a PR ;)

**Comment by etaty** [comment]
fixed in 1.6.0
