### ISSUE TITLE
async call does not allow specification of timeout

### ISSUE THREAD

**Issue by johanatan** [etaty/rediscala#72]
It should rather require that an implicit Timeout be in scope like the rest of Akka.

**Comment by etaty** [comment]
We don't need a timeout, if the connection fail (is reset), then we will fail the promises.

Let's suppose i have a command, and this command is executed on Redis server, but the promise fail because it timeout in the actor system. Will you write the code to recover from that ?

And if you are not convinced, you can build your own timeout wrapper.

**Comment by johanatan** [comment]
I don't need to recover-- I just need to fail more quickly than 40 seconds. Can you tell me how to adjust the timeout from 40 seconds to say 2 seconds?

**Comment by etaty** [comment]
Where does the 40s come from ?

http://doc.akka.io/docs/akka/snapshot/scala/futures.html see After

**Comment by johanatan** [comment]
after has nothing to do with this. I do not want to delay the computation of anything. The 40s comes from my web request framework timing out further upstream from the redis call. I do not want my entire web request to timeout but rather for the call to redis to timeout.

**Comment by etaty** [comment]
```scala
val delayed = akka.pattern.after(2 seconds, using = system.scheduler)(Future.failed(
new IllegalStateException("OHNOES")))
val valueF = redis.get("key")
val result = Future firstCompletedOf Seq(valueF, delayed)
```

**Comment by johanatan** [comment]
That would work but does firstCompletedOf kill the outstanding futures that were not completed? If not, I imagine that could be a resource leakage we would not want.

**Comment by etaty** [comment]
This code won't cancel the slowest future. 
And I don't know how to cancel a TCP packet (once it is on the network) nor revert a redis command ;)
That's why i don't like timeout.
