### ISSUE TITLE
can we publish to maven central

### ISSUE THREAD

**Issue by mohnishkodnani** [etaty/rediscala#81]
Can we publish this to maven central, I want to use it but our policies dont allow bintray.

**Comment by brett-shwom** [comment]
+1

**Comment by ariskk** [comment]
+1

**Comment by scravy** [comment]
+1

**Comment by etaty** [comment]
It's in progress https://issues.sonatype.org/browse/OSSRH-19060

**Comment by etaty** [comment]
And it's done

```scala
libraryDependencies ++= Seq(
  "com.github.etaty" %% "rediscala" % "1.5.0"
)
```

I am using for [rediscala-demo](https://github.com/etaty/rediscala-demo)
