### ISSUE TITLE
Reconnect in pubsub system ?

### ISSUE THREAD

**Issue by lahirug** [etaty/rediscala#84]
If the connection to the redis is lost, does the library reconnect automatically or we should implement it ?

**Comment by etaty** [comment]
It does reconnect, it tries every 2 seconds.

**Comment by lahirug** [comment]
If there was a subscription do we get the messages after reconnect ?

Thank you for the response !

**Comment by etaty** [comment]
yes, you will have the same subscriptions, but messages can be lost.
Redis PubSub does not keep message around, redis just push to current subscribers

**Comment by lahirug** [comment]
That is a great news. I started with very first example and it doesn't work
and give me this error.

Error:scalac: there was one feature warning; re-run with -feature for
details

**Comment by etaty** [comment]
I can't see the error message (maybe do a gist) ?

**Comment by etaty** [comment]
https://github.com/etaty/rediscala-demo/blob/master/src/main/scala/ExamplePubSub.scala

**Comment by lahirug** [comment]
@etaty Thanks for the prompt responses so far. Before I will test samples, just curious even if the redis server is restarted still do we reconnect and keep the subscriptions active ?

**Comment by lahirug** [comment]
@etaty it just worked, I tested locally, thats what I want. Thanks !
