### ISSUE TITLE
Discrepancy between ZADD and ZRANGE score types

### ISSUE THREAD

**Issue by maciej** [etaty/rediscala#97]
In rediscala 1.4.0 ZADD expects memeber scores to be of type `Double`, whereas ZRANGE expects `start` and `stop` to be `Long`s. Is that intended?

See [`commands/SortedSets.scala`](https://github.com/etaty/rediscala/blob/master/src/main/scala/redis/commands/SortedSets.scala).

**Comment by etaty** [comment]
Yes it is
You want `zrangebyscore` http://redis.io/commands/zrangebyscore


> http://redis.io/commands/zrange
> Both start and stop are zero-based indexes, where 0 is the first element, 1 is the next element and so on.

**Comment by maciej** [comment]
@etaty thank you for a quick response! So yes, I mixed up the Redis commands. :-)
